# Generated by Django 5.2.8 on 2025-11-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profession',
        ),
        migrations.AddField(
            model_name='profile',
            name='professions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='profilePhoto',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
