# Generated by Django 5.2.8 on 2025-11-27 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='eduction',
            new_name='education',
        ),
    ]
