# Generated by Django 5.2.8 on 2025-12-03 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_profile_professions_about_education_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('BACKEND', 'Backend'), ('FRONTEND', 'Frontend'), ('OTHER', 'Other Skills')], default='OTHER', max_length=50)),
                ('item', models.CharField(max_length=50)),
                ('proficiency', models.IntegerField(default=50, help_text='Proficiency level from 0 to 100')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='app.profile')),
            ],
        ),
    ]
