# Generated by Django 5.2.8 on 2025-12-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='details',
            field=models.JSONField(default=list),
        ),
    ]
