# Generated by Django 5.2.8 on 2025-12-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_experience_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='details',
            field=models.JSONField(default=list, null=True),
        ),
    ]
