# Generated by Django 5.2.8 on 2025-12-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_experience_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='details',
            field=models.JSONField(default=list, null=True),
        ),
    ]
