# Generated by Django 5.2.8 on 2025-12-06 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_internship_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='projectImage/')),
                ('category', models.CharField(choices=[('django', 'Django'), ('python', 'Python'), ('fullstack', 'Full Stack'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('tech', models.CharField(default=list)),
                ('features', models.CharField(default=list)),
                ('link', models.URLField(blank=True, null=True)),
                ('code', models.URLField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='app.profile')),
            ],
        ),
    ]
